language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    secure: "QLx262WXvB6oXDYzHVkD8mmPzs6F8H3+WqFX4YKQBgg/WBuU/2mxxNLxqrfa6dHAPAAyWZDyejFk6xLwL4mApBhu4CfHQSybeWEKMijsO0x/f6MMtiIRWzjHuxicsdpwQdnmMeJGkpnWeDPUls1alphGf57DmUPheOOyKzKrRTcc7iUt1i20bc4Ilw5J9AwXLedaQ2TcKScq42ZCnM7y1Mt/sKO+wWik+n7/gVu74bTnVqBQC2KKj2jkVPtpmMhfazgKHDFTPGf3YtLpZW/GnweP34j35kdD8OPyKqqzg0O+N4obI3J/asWshQ5wOquX2sJdLaGQtkQou1dVSJgcplZ1NsvRj5DPLkDohyBmGJGVgCJu+fLVyhQT0N66nlApJQMbsZpeQiK1NNbAJhy2ySLmM90byopSaSgCPnS7BUBvK1FnLIMNyn/ZTwu65zSZhWsZ6J5pKZLILA269Zw+2+Ws8sK3EEx3Fl0bXWStcDpiBJn7hpJ25zdkiOg6bjHfCMCApvePV5MOqa/Ar9FXtEE/bYi85XAcQZve1dFKcpG5Yi/NG/fvGeNHuXxtZGp5XE1dwz7c6ox0PxfZyXo9qby1/h8peKasO9ndlLkZitXrvKt74aW/JnVcvsAZPcQ/8a17vYrMrBBwXnIMDLks7cFGSFsQ5TibY7KL+Yv3cco="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

